const createHttpError = require('http-errors')
const { User } = require('../../database/models')
const { endpointResponse } = require('../../helpers/success')
const { catchAsync } = require('../../helpers/catchAsync')


module.exports = {
    deleteUser: catchAsync((async (req, res, next) => {
        const { id } = req.params

        const user = await user.findByPk(id)

        if (user != null) {
            try {
                const responce = await User.destroy({
                    where: { id }
                })
                endpointResponse({
                    res,
                    message: 'User Deleted',
                    body: responce,
                })
            } catch (error) {
                const httpError = createHttpError(
                    error.statusCode,
                    `[Error deleted User: ${error.message}`
                )
            }
        }
    })),
}